import { ReactElement } from 'react';
import {
  AlertCircle,
  ShieldAlert,
  SlidersHorizontal,
  Gauge,
  Captions,
  Cast,
  UserPlus,
  KeyRound,
  Link as LinkIcon,
  Users,
  Users2,
  Gamepad2,
  List,
  Download,
  Puzzle,
  Smartphone,
  Github,
  Crown,
  Unlock,
  HardDriveDownload,
  Globe,
  Tv,
  Filter,
  ListOrdered,
  Palette,
  History,
} from 'lucide-react';
import CaMarchePlusPage from './CaMarchePlusPage';
import DnsPage from './DnsPage';
import ChangerLecteurPage from './ChangerLecteurPage';
import QualiteVideoPage from './QualiteVideoPage';
import SousTitresPage from './SousTitresPage';
import ChromecastPage from './ChromecastPage';
import ComptePage from './ComptePage';
import RecupererComptePage from './RecupererComptePage';
import LierComptePage from './LierComptePage';
import ProfilsPage from './ProfilsPage';
import WatchpartyPage from './WatchpartyPage';
import ListesPartageesPage from './ListesPartageesPage';
import InstallerPwaPage from './InstallerPwaPage';
import ExtensionPage from './ExtensionPage';
import PremidPage from './PremidPage';
import AppMobilePage from './AppMobilePage';
import OpenSourcePage from './OpenSourcePage';
import VipHelpPage from './VipHelpPage';
import DebridHelpPage from './DebridHelpPage';
import TelechargementPage from './TelechargementPage';
import MiroirsPage from './MiroirsPage';
import LiveTvHelpPage from './LiveTvHelpPage';
import ExtractionPage from './ExtractionPage';
import PrioriteSourcesPage from './PrioriteSourcesPage';
import DernierLecteurPage from './DernierLecteurPage';
import ApparencePage from './ApparencePage';

export type TutoAccent = 'red' | 'blue' | 'green' | 'orange' | 'purple';

export interface TutoMeta {
  /** URL slug — full path is /help/<slug> */
  slug: string;
  /** The React component to render when this tuto is active */
  component: React.ComponentType;
  /** i18n key for the hub card title */
  titleKey: string;
  /** i18n key for the hub card subtitle */
  subKey: string;
  /** Icon element rendered on the hub card (sized by the hub via className) */
  icon: ReactElement;
  /** Color accent for the card border + icon tint */
  accent: TutoAccent;
  /**
   * i18n keys whose resolved values are indexed for the search feature on
   * the hub page. Include the title, hero sub, and every body paragraph so
   * users can find the tuto by any keyword appearing in the content.
   */
  searchKeys: string[];
}

export const TUTO_REGISTRY: TutoMeta[] = [
  {
    slug: 'ca-marche-plus',
    component: CaMarchePlusPage,
    titleKey: 'help.hub.cardCaMarchePlusTitle',
    subKey: 'help.hub.cardCaMarchePlusSub',
    icon: <AlertCircle className="w-8 h-8" />,
    accent: 'red',
    searchKeys: [
      'help.caMarchePlus.title',
      'help.caMarchePlus.heroSub',
      'help.caMarchePlus.intro',
      'help.caMarchePlus.cause1Title',
      'help.caMarchePlus.cause1Body',
      'help.caMarchePlus.cause2Title',
      'help.caMarchePlus.cause2Body',
      'help.caMarchePlus.cause3Title',
      'help.caMarchePlus.cause3Body',
      'help.caMarchePlus.cause4Title',
      'help.caMarchePlus.cause4Body',
    ],
  },
  {
    slug: 'dns',
    component: DnsPage,
    titleKey: 'help.hub.cardDnsTitle',
    subKey: 'help.hub.cardDnsSub',
    icon: <ShieldAlert className="w-8 h-8" />,
    accent: 'red',
    searchKeys: [
      'helpDns.title',
      'helpDns.heroSub',
      'helpDns.whyTitle',
      'helpDns.whyBody',
      'helpDns.solutionTitle',
      'helpDns.solutionBody',
      'helpDns.installIos',
      'helpDns.installIosBody',
      'helpDns.installAndroid',
      'helpDns.installAndroidBody',
      'helpDns.installWindows',
      'helpDns.installWindowsBody',
      'helpDns.installMac',
      'helpDns.installMacBody',
      'helpDns.installLinux',
      'helpDns.installLinuxBody',
    ],
  },
  {
    slug: 'changer-lecteur',
    component: ChangerLecteurPage,
    titleKey: 'help.hub.cardChangerLecteurTitle',
    subKey: 'help.hub.cardChangerLecteurSub',
    icon: <SlidersHorizontal className="w-8 h-8" />,
    accent: 'blue',
    searchKeys: [
      'help.changerLecteur.title',
      'help.changerLecteur.heroSub',
      'help.changerLecteur.introBody',
      'help.changerLecteur.diffHlsBody',
      'help.changerLecteur.diffEmbedBody',
      'help.changerLecteur.step1',
      'help.changerLecteur.step2',
      'help.changerLecteur.step3',
    ],
  },
  {
    slug: 'qualite-video',
    component: QualiteVideoPage,
    titleKey: 'help.hub.cardQualiteVideoTitle',
    subKey: 'help.hub.cardQualiteVideoSub',
    icon: <Gauge className="w-8 h-8" />,
    accent: 'green',
    searchKeys: [
      'help.qualiteVideo.title',
      'help.qualiteVideo.heroSub',
      'help.qualiteVideo.introBody',
      'help.qualiteVideo.hlsBody1',
      'help.qualiteVideo.hlsBody2',
      'help.qualiteVideo.hlsBody3',
      'help.qualiteVideo.embedIntro',
      'help.qualiteVideo.checkYourselfBody',
      'help.qualiteVideo.tipBody',
      'help.qualiteVideo.providerUqload',
      'help.qualiteVideo.providerSibnet',
      'help.qualiteVideo.providerVoe',
      'help.qualiteVideo.providerSupervideo',
      'help.qualiteVideo.providerVidzy',
      'help.qualiteVideo.providerDoodstream',
      'help.qualiteVideo.providerSeekstream',
      'help.qualiteVideo.providerVidplay',
    ],
  },
  {
    slug: 'sous-titres',
    component: SousTitresPage,
    titleKey: 'help.hub.cardSousTitresTitle',
    subKey: 'help.hub.cardSousTitresSub',
    icon: <Captions className="w-8 h-8" />,
    accent: 'blue',
    searchKeys: [
      'help.sousTitres.title',
      'help.sousTitres.heroSub',
      'help.sousTitres.introBody',
      'help.sousTitres.hlsBody',
      'help.sousTitres.externalBody',
      'help.sousTitres.translateBody',
      'help.sousTitres.embedBody',
    ],
  },
  {
    slug: 'chromecast',
    component: ChromecastPage,
    titleKey: 'help.hub.cardChromecastTitle',
    subKey: 'help.hub.cardChromecastSub',
    icon: <Cast className="w-8 h-8" />,
    accent: 'blue',
    searchKeys: [
      'help.chromecast.title',
      'help.chromecast.heroSub',
      'help.chromecast.introBody',
      'help.chromecast.chromecastBody',
      'help.chromecast.airplayBody',
      'help.chromecast.limitsBody',
    ],
  },
  {
    slug: 'compte',
    component: ComptePage,
    titleKey: 'help.hub.cardCompteTitle',
    subKey: 'help.hub.cardCompteSub',
    icon: <UserPlus className="w-8 h-8" />,
    accent: 'green',
    searchKeys: [
      'help.compte.title',
      'help.compte.heroSub',
      'help.compte.whyBody',
      'help.compte.step1',
      'help.compte.step2',
      'help.compte.step3',
      'help.compte.step4',
      'help.compte.warningBody',
      'help.compte.oauthBody',
    ],
  },
  {
    slug: 'recuperer-compte',
    component: RecupererComptePage,
    titleKey: 'help.hub.cardRecupererCompteTitle',
    subKey: 'help.hub.cardRecupererCompteSub',
    icon: <KeyRound className="w-8 h-8" />,
    accent: 'red',
    searchKeys: [
      'help.recupererCompte.title',
      'help.recupererCompte.heroSub',
      'help.recupererCompte.warningBody',
      'help.recupererCompte.whyBody',
      'help.recupererCompte.ifLostBody',
      'help.recupererCompte.preventBody',
      'help.recupererCompte.supportBody',
    ],
  },
  {
    slug: 'lier-compte',
    component: LierComptePage,
    titleKey: 'help.hub.cardLierCompteTitle',
    subKey: 'help.hub.cardLierCompteSub',
    icon: <LinkIcon className="w-8 h-8" />,
    accent: 'purple',
    searchKeys: [
      'help.lierCompte.title',
      'help.lierCompte.heroSub',
      'help.lierCompte.introBody',
      'help.lierCompte.step1',
      'help.lierCompte.step2',
      'help.lierCompte.step3',
      'help.lierCompte.step4',
      'help.lierCompte.limitsBody',
      'help.lierCompte.securityBody',
    ],
  },
  {
    slug: 'profils',
    component: ProfilsPage,
    titleKey: 'help.hub.cardProfilsTitle',
    subKey: 'help.hub.cardProfilsSub',
    icon: <Users2 className="w-8 h-8" />,
    accent: 'purple',
    searchKeys: [
      'help.profils.title',
      'help.profils.heroSub',
      'help.profils.introBody',
      'help.profils.step1',
      'help.profils.step2',
      'help.profils.step3',
      'help.profils.step4',
      'help.profils.ageTableIntro',
      'help.profils.ageTableNote',
      'help.profils.kidsBody',
      'help.profils.switchBody',
      'help.profils.limitsBody',
    ],
  },
  {
    slug: 'watchparty',
    component: WatchpartyPage,
    titleKey: 'help.hub.cardWatchpartyTitle',
    subKey: 'help.hub.cardWatchpartySub',
    icon: <Users className="w-8 h-8" />,
    accent: 'orange',
    searchKeys: [
      'help.watchparty.title',
      'help.watchparty.heroSub',
      'help.watchparty.introBody',
      'help.watchparty.step1',
      'help.watchparty.step2',
      'help.watchparty.step3',
      'help.watchparty.constraintsBody',
      'help.watchparty.incompatBody',
      'help.watchparty.nightflixNoteBody',
      'help.watchparty.syncBody',
    ],
  },
  {
    slug: 'listes-partagees',
    component: ListesPartageesPage,
    titleKey: 'help.hub.cardListesPartageesTitle',
    subKey: 'help.hub.cardListesPartageesSub',
    icon: <List className="w-8 h-8" />,
    accent: 'purple',
    searchKeys: [
      'help.listesPartagees.title',
      'help.listesPartagees.heroSub',
      'help.listesPartagees.introBody',
      'help.listesPartagees.step1',
      'help.listesPartagees.step2',
      'help.listesPartagees.step3',
      'help.listesPartagees.shareBody',
      'help.listesPartagees.collabBody',
      'help.listesPartagees.catalogBody',
    ],
  },
  {
    slug: 'installer-pwa',
    component: InstallerPwaPage,
    titleKey: 'help.hub.cardInstallerPwaTitle',
    subKey: 'help.hub.cardInstallerPwaSub',
    icon: <Download className="w-8 h-8" />,
    accent: 'green',
    searchKeys: [
      'help.installerPwa.title',
      'help.installerPwa.heroSub',
      'help.installerPwa.introBody',
      'help.installerPwa.iosBody',
      'help.installerPwa.androidBody',
      'help.installerPwa.desktopBody',
      'help.installerPwa.advantagesBody',
    ],
  },
  {
    slug: 'extension',
    component: ExtensionPage,
    titleKey: 'help.hub.cardExtensionTitle',
    subKey: 'help.hub.cardExtensionSub',
    icon: <Puzzle className="w-8 h-8" />,
    accent: 'orange',
    searchKeys: [
      'help.extension.title',
      'help.extension.heroSub',
      'help.extension.introBody',
      'help.extension.chromeBody',
      'help.extension.firefoxBody',
      'help.extension.permissionsBody',
      'help.extension.limitsBody',
    ],
  },
  {
    slug: 'premid',
    component: PremidPage,
    titleKey: 'help.hub.cardPremidTitle',
    subKey: 'help.hub.cardPremidSub',
    icon: <Gamepad2 className="w-8 h-8" />,
    accent: 'purple',
    searchKeys: [
      'help.premid.title',
      'help.premid.heroSub',
      'help.premid.introBody',
      'help.premid.installBody',
      'help.premid.step1',
      'help.premid.step2',
      'help.premid.step3',
      'help.premid.step4',
      'help.premid.LKSTVPresenceBody',
      'help.premid.limitsBody',
    ],
  },
  {
    slug: 'app-mobile',
    component: AppMobilePage,
    titleKey: 'help.hub.cardAppMobileTitle',
    subKey: 'help.hub.cardAppMobileSub',
    icon: <Smartphone className="w-8 h-8" />,
    accent: 'green',
    searchKeys: [
      'help.appMobile.title',
      'help.appMobile.heroSub',
      'help.appMobile.introBody',
      'help.appMobile.downloadBody',
      'help.appMobile.step1',
      'help.appMobile.step2',
      'help.appMobile.step3',
      'help.appMobile.updatesBody',
      'help.appMobile.iosBody',
    ],
  },
  {
    slug: 'open-source',
    component: OpenSourcePage,
    titleKey: 'help.hub.cardOpenSourceTitle',
    subKey: 'help.hub.cardOpenSourceSub',
    icon: <Github className="w-8 h-8" />,
    accent: 'purple',
    searchKeys: [
      'help.openSource.title',
      'help.openSource.heroSub',
      'help.openSource.introBody',
      'help.openSource.contentBody',
      'help.openSource.whyBody',
      'help.openSource.selfhostBody',
      'help.openSource.contribBody',
      'help.openSource.limitsBody',
    ],
  },
  {
    slug: 'vip',
    component: VipHelpPage,
    titleKey: 'help.hub.cardVipTitle',
    subKey: 'help.hub.cardVipSub',
    icon: <Crown className="w-8 h-8" />,
    accent: 'orange',
    searchKeys: [
      'help.vip.title',
      'help.vip.heroSub',
      'help.vip.introBody',
      'help.vip.perksBody',
      'help.vip.packsIntro',
      'help.vip.paymentBody',
      'help.vip.step1',
      'help.vip.step2',
      'help.vip.step3',
      'help.vip.step4',
      'help.vip.giftBody',
      'help.vip.invoicesBody',
      'help.vip.limitsBody',
    ],
  },
  {
    slug: 'debrid',
    component: DebridHelpPage,
    titleKey: 'help.hub.cardDebridTitle',
    subKey: 'help.hub.cardDebridSub',
    icon: <Unlock className="w-8 h-8" />,
    accent: 'orange',
    searchKeys: [
      'help.debrid.title',
      'help.debrid.heroSub',
      'help.debrid.introBody',
      'help.debrid.vipBody',
      'help.debrid.supportedBody',
      'help.debrid.providersBody',
      'help.debrid.step1',
      'help.debrid.step2',
      'help.debrid.step3',
      'help.debrid.step4',
      'help.debrid.historyBody',
      'help.debrid.limitsBody',
    ],
  },
  {
    slug: 'telechargement',
    component: TelechargementPage,
    titleKey: 'help.hub.cardTelechargementTitle',
    subKey: 'help.hub.cardTelechargementSub',
    icon: <HardDriveDownload className="w-8 h-8" />,
    accent: 'blue',
    searchKeys: [
      'help.telechargement.title',
      'help.telechargement.heroSub',
      'help.telechargement.introBody',
      'help.telechargement.step1',
      'help.telechargement.step2',
      'help.telechargement.step3',
      'help.telechargement.step4',
      'help.telechargement.hostsBody',
      'help.telechargement.debridBody',
      'help.telechargement.seriesBody',
      'help.telechargement.limitsBody',
    ],
  },
  {
    slug: 'miroirs',
    component: MiroirsPage,
    titleKey: 'help.hub.cardMiroirsTitle',
    subKey: 'help.hub.cardMiroirsSub',
    icon: <Globe className="w-8 h-8" />,
    accent: 'red',
    searchKeys: [
      'help.miroirs.title',
      'help.miroirs.heroSub',
      'help.miroirs.introBody',
      'help.miroirs.howBody',
      'help.miroirs.officialListBody',
      'help.miroirs.newDeviceBody',
      'help.miroirs.reliabilityBody',
      'help.miroirs.limitsBody',
    ],
  },
  {
    slug: 'live-tv',
    component: LiveTvHelpPage,
    titleKey: 'help.hub.cardLiveTvTitle',
    subKey: 'help.hub.cardLiveTvSub',
    icon: <Tv className="w-8 h-8" />,
    accent: 'purple',
    searchKeys: [
      'help.liveTv.title',
      'help.liveTv.heroSub',
      'help.liveTv.introBody',
      'help.liveTv.sourcesBody',
      'help.liveTv.categoriesIntro',
      'help.liveTv.catGeneralisteExample',
      'help.liveTv.catCinemaExample',
      'help.liveTv.catInfoExample',
      'help.liveTv.catSportExample',
      'help.liveTv.catEnfantsExample',
      'help.liveTv.catMusiqueExample',
      'help.liveTv.catDocuExample',
      'help.liveTv.matchesBody',
      'help.liveTv.favoritesBody',
      'help.liveTv.extensionBody',
      'help.liveTv.limitsBody',
    ],
  },
  {
    slug: 'extraction',
    component: ExtractionPage,
    titleKey: 'help.hub.cardExtractionTitle',
    subKey: 'help.hub.cardExtractionSub',
    icon: <Filter className="w-8 h-8" />,
    accent: 'orange',
    searchKeys: [
      'help.extraction.title',
      'help.extraction.heroSub',
      'help.extraction.introBody',
      'help.extraction.whereBody',
      'help.extraction.step1',
      'help.extraction.step2',
      'help.extraction.step3',
      'help.extraction.cacheBody',
      'help.extraction.noExtensionBody',
      'help.extraction.limitsBody',
    ],
  },
  {
    slug: 'priorite-sources',
    component: PrioriteSourcesPage,
    titleKey: 'help.hub.cardPrioriteSourcesTitle',
    subKey: 'help.hub.cardPrioriteSourcesSub',
    icon: <ListOrdered className="w-8 h-8" />,
    accent: 'red',
    searchKeys: [
      'help.prioriteSources.title',
      'help.prioriteSources.heroSub',
      'help.prioriteSources.introBody',
      'help.prioriteSources.whereBody',
      'help.prioriteSources.step1',
      'help.prioriteSources.step2',
      'help.prioriteSources.step3',
      'help.prioriteSources.step4',
      'help.prioriteSources.pinBody',
      'help.prioriteSources.overrideBody',
      'help.prioriteSources.advancedBody',
      'help.prioriteSources.resetBody',
      'help.prioriteSources.syncBody',
      'help.prioriteSources.limitsBody',
    ],
  },
  {
    slug: 'dernier-lecteur',
    component: DernierLecteurPage,
    titleKey: 'help.hub.cardDernierLecteurTitle',
    subKey: 'help.hub.cardDernierLecteurSub',
    icon: <History className="w-8 h-8" />,
    accent: 'blue',
    searchKeys: [
      'help.dernierLecteur.title',
      'help.dernierLecteur.heroSub',
      'help.dernierLecteur.introBody',
      'help.dernierLecteur.howBody',
      'help.dernierLecteur.priorityBody',
      'help.dernierLecteur.fallbackBody',
      'help.dernierLecteur.limitsBody',
    ],
  },
  {
    slug: 'apparence',
    component: ApparencePage,
    titleKey: 'help.hub.cardApparenceTitle',
    subKey: 'help.hub.cardApparenceSub',
    icon: <Palette className="w-8 h-8" />,
    accent: 'purple',
    searchKeys: [
      'help.apparence.title',
      'help.apparence.heroSub',
      'help.apparence.introBody',
      'help.apparence.bgStyleBody',
      'help.apparence.bgColorBody',
      'help.apparence.smoothScrollBody',
      'help.apparence.scrollPositionBody',
      'help.apparence.soundBody',
      'help.apparence.commentsBody',
      'help.apparence.heroBody',
      'help.apparence.snowBody',
      'help.apparence.screensaverBody',
      'help.apparence.introAnimationBody',
      'help.apparence.sidebarBody',
      'help.apparence.limitsBody',
    ],
  },
];
